#!/bin/bash
source ./lib.sh

HOME_PATH="/home"

REPAIRQ_LOCAL_PROJECTS_DIR_SUFFIX="/Projects/repairq"
REPAIRQ_LOCAL_PROJECTS_DIR=${HOME}${REPAIRQ_LOCAL_PROJECTS_DIR_SUFFIX}
REPAIRQ_LOCAL_SN=${HOME}"/rq"

REPAIRQ_DOCKER_REPOSITORY_CLONE=0
REPAIRQ_DOCKER_REPOSITORY_NEW_BRANCH_CHECKOUT=0
REPAIRQ_DOCKER_REPOSITORY_NEW_BRANCH_RSYNC=0
REPAIRQ_DOCKER_LINUX_TEMPLATE_DIR="linux-tpl"
REPAIRQ_DOCKER_REPOSITORY_URL="https://github.com/RepairQ/RepairQ-Docker.git"
REPAIRQ_DOCKER_DIR_SUFFIX="/RepairQ-Docker"
REPAIRQ_DOCKER_DIR=${REPAIRQ_LOCAL_PROJECTS_DIR}${REPAIRQ_DOCKER_DIR_SUFFIX}
REPAIRQ_USER_SPECIFIC_DOCKER_DIR=""

echo $'Starting the installation\n'

check_requirements
#create_work_dir
#clone_docker_repo
#new_branch_checkout
configure_installation_files

echo $'\nInstallation finished'